# netlify.toml  (리포 루트)
[build]
  # 정적 사이트면 별도 빌드 커맨드가 없다면 비워둬도 OK
  publish = "."

[dev]
  functions = "netlify/functions"
  framework = "#static"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mysql2"]
  functions = "netlify/functions"
  framework = "#static"
  port = 8888

[build.environment]
  NODE_VERSION = "20"

# --- 메인 랜딩: /  -> mainpage-website/index.html
[[redirects]]
  from = "/"
  to = "/mainpage-website/index.html"
  status = 200

# --- 정적 파일 직접 서빙
[[redirects]]
  from = "/styles.css"
  to = "/mainpage-website/styles.css"
  status = 200

[[redirects]]
  from = "/script.js"
  to = "/mainpage-website/script.js"
  status = 200

# --- 개별 섹션: 정적 파일 직접 제공
#    SPA면 index.html로 고정 라우팅(200) / 정적만이면 301/200 혼합 가능

# /ranking ... (SPA 라우팅 가정)
[[redirects]]
  from = "/ranking"
  to = "/ranking/index.html"
  status = 200
[[redirects]]
  from = "/ranking/*"
  to = "/ranking/index.html"
  status = 200

# /sale ...
[[redirects]]
  from = "/sale"
  to = "/sale/index.html"
  status = 200
[[redirects]]
  from = "/sale/*"
  to = "/sale/index.html"
  status = 200

# /Detail ...
[[redirects]]
  from = "/Detail"
  to = "/Detail/index.html"
  status = 200
[[redirects]]
  from = "/Detail/*"
  to = "/Detail/index.html"
  status = 200

# /Detailpage ...
[[redirects]]
  from = "/Detailpage"
  to = "/Detailpage/index.html"
  status = 200
[[redirects]]
  from = "/Detailpage/*"
  to = "/Detailpage/index.html"
  status = 200

# /cart ...
[[redirects]]
  from = "/cart"
  to = "/cart/index.html"
  status = 200
[[redirects]]
  from = "/cart/*"
  to = "/cart/index.html"
  status = 200

# /fitpl-website ...
[[redirects]]
  from = "/fitpl-website"
  to = "/fitpl-website/index.html"
  status = 200
[[redirects]]
  from = "/fitpl-website/*"
  to = "/fitpl-website/index.html"
  status = 200

# --- 정적 파일 헤더 설정
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

# --- 서버리스 API (예: /.netlify/functions/hello)
# 별도 설정 불필요. netlify/functions/hello.mjs 파일만 있으면
# /.netlify/functions/hello 로 자동 라우팅됨.
