# netlify.toml (repo root)

[build]
  publish   = "mainpage-website"      # index.html 있는 폴더
  functions = "netlify/functions"     # 함수 폴더 위치

[dev]
  framework = "#static"
  port      = 8888
  functions = "netlify/functions"

[functions]
  node_bundler          = "esbuild"
  external_node_modules = ["mysql2"]

[build.environment]
  NODE_VERSION = "20"

# ------ 라우팅/헤더 (필요하면 유지) ------
[[redirects]]
  from = "/"
  to   = "/mainpage-website/index.html"
  status = 200

[[redirects]]
  from = "/styles.css"
  to   = "/mainpage-website/styles.css"
  status = 200

[[redirects]]
  from = "/script.js"
  to   = "/mainpage-website/script.js"
  status = 200

[[redirects]]  # ranking
  from = "/ranking"
  to   = "/ranking/index.html"
  status = 200
[[redirects]]
  from = "/ranking/*"
  to   = "/ranking/index.html"
  status = 200

[[redirects]]  # sale
  from = "/sale"
  to   = "/sale/index.html"
  status = 200
[[redirects]]
  from = "/sale/*"
  to   = "/sale/index.html"
  status = 200

[[redirects]]  # Detail
  from = "/Detail"
  to   = "/Detail/index.html"
  status = 200
[[redirects]]
  from = "/Detail/*"
  to   = "/Detail/index.html"
  status = 200

[[redirects]]  # Detailpage
  from = "/Detailpage"
  to   = "/Detailpage/index.html"
  status = 200
[[redirects]]
  from = "/Detailpage/*"
  to   = "/Detailpage/index.html"
  status = 200

[[redirects]]  # cart
  from = "/cart"
  to   = "/cart/index.html"
  status = 200
[[redirects]]
  from = "/cart/*"
  to   = "/cart/index.html"
  status = 200

[[redirects]]  # fitpl-website
  from = "/fitpl-website"
  to   = "/fitpl-website/index.html"
  status = 200
[[redirects]]
  from = "/fitpl-website/*"
  to   = "/fitpl-website/index.html"
  status = 200

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
